INSERT IGNORE INTO roles(name) VALUES('ROLE_ADMIN');
INSERT IGNORE INTO roles(name) VALUES('ROLE_PATIENT');
INSERT IGNORE INTO roles(name) VALUES('ROLE_MEDICAL_STAFF');
INSERT IGNORE INTO roles(name) VALUES('ROLE_DOCTOR');
INSERT IGNORE INTO roles(name) VALUES('ROLE_NURSE');
INSERT IGNORE INTO roles(name) VALUES('ROLE_CLINIC_ADMIN');
INSERT IGNORE INTO roles(name) VALUES('ROLE_CLINIC_CENTER_ADMIN');
